for i in 1 2 3 4 5
do
java Main concurrentHash 1 0.25 >> dadosDasEstruturas.txt
java Main concurrentHash 1 0.5 >> dadosDasEstruturas.txt
java Main concurrentHash 1 0.75 >> dadosDasEstruturas.txt
java Main concurrentHash 1 1 >> dadosDasEstruturas.txt
java Main concurrentHash 128 0.25 >> dadosDasEstruturas.txt
java Main concurrentHash 128 0.5 >> dadosDasEstruturas.txt
java Main concurrentHash 128 0.75 >> dadosDasEstruturas.txt
java Main concurrentHash 128 1 >> dadosDasEstruturas.txt
java Main concurrentHash 512 0.25 >> dadosDasEstruturas.txt
java Main concurrentHash 512 0.5 >> dadosDasEstruturas.txt
java Main concurrentHash 512 0.75 >> dadosDasEstruturas.txt
java Main concurrentHash 512 1 >> dadosDasEstruturas.txt
java Main synchronizedMap 1 0.25 >> dadosDasEstruturas.txt
java Main synchronizedMap 1 0.5 >> dadosDasEstruturas.txt
java Main synchronizedMap 1 0.75 >> dadosDasEstruturas.txt
java Main synchronizedMap 1 1 >> dadosDasEstruturas.txt
java Main synchronizedMap 128 0.25 >> dadosDasEstruturas.txt
java Main synchronizedMap 128 0.5 >> dadosDasEstruturas.txt
java Main synchronizedMap 128 0.75 >> dadosDasEstruturas.txt
java Main synchronizedMap 128 1 >> dadosDasEstruturas.txt
java Main synchronizedMap 512 0.25 >> dadosDasEstruturas.txt
java Main synchronizedMap 512 0.5 >> dadosDasEstruturas.txt
java Main synchronizedMap 512 0.75 >> dadosDasEstruturas.txt
java Main synchronizedMap 512 1 >> dadosDasEstruturas.txt
java Main copyOnWriteList 1 0.25 >> dadosDasEstruturas.txt
java Main copyOnWriteList 1 0.5 >> dadosDasEstruturas.txt
java Main copyOnWriteList 1 0.75 >> dadosDasEstruturas.txt
java Main copyOnWriteList 1 1 >> dadosDasEstruturas.txt
java Main copyOnWriteList 128 0.25 >> dadosDasEstruturas.txt
java Main copyOnWriteList 128 0.5 >> dadosDasEstruturas.txt
java Main copyOnWriteList 128 0.75 >> dadosDasEstruturas.txt
java Main copyOnWriteList 128 1 >> dadosDasEstruturas.txt
java Main copyOnWriteList 512 0.25 >> dadosDasEstruturas.txt
java Main copyOnWriteList 512 0.5 >> dadosDasEstruturas.txt
java Main copyOnWriteList 512 0.75 >> dadosDasEstruturas.txt
java Main copyOnWriteList 512 1 >> dadosDasEstruturas.txt
java Main synchronizedList 1 0.25 >> dadosDasEstruturas.txt
java Main synchronizedList 1 0.5 >> dadosDasEstruturas.txt
java Main synchronizedList 1 0.75 >> dadosDasEstruturas.txt
java Main synchronizedList 1 1 >> dadosDasEstruturas.txt
java Main synchronizedList 128 0.25 >> dadosDasEstruturas.txt
java Main synchronizedList 128 0.5 >> dadosDasEstruturas.txt
java Main synchronizedList 128 0.75 >> dadosDasEstruturas.txt
java Main synchronizedList 128 1 >> dadosDasEstruturas.txt
java Main synchronizedList 512 0.25 >> dadosDasEstruturas.txt
java Main synchronizedList 512 0.5 >> dadosDasEstruturas.txt
java Main synchronizedList 512 0.75 >> dadosDasEstruturas.txt
java Main synchronizedList 512 1 >> dadosDasEstruturas.txt
done